# Database
POSTGRESQL_USERNAME: user
POSTGRESQL_PASSWORD: letmein
POSTGRESQL_HOST: 192.168.1.80
POSTGRESQL_PORT: 5432
POSTGRESQL_DATABASE: docdatabase

# Server
SERVER_PORT: 8085
ACTIVE_PROFILE: dev

# Email Configuration
EMAIL_HOST: smtp.gmail.com
EMAIL_PORT: 587
EMAIL_USERNAME: leehscott24@gmail.com
EMAIL_PASSWORD: smqm vgnz mzto gqlz
VERIFY_EMAIL_HOST: http://localhost:8085 # Change to 3000 or React port'

JWT_SECRET: ${SECRET}
JWT_EXPIRATION: 432_000_000